version: "3.8"

services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181"
  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      HOSTNAME_COMMAND: "/sbin/ip route|awk '/default/ { print $$3 }'"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock